version: '3.8'

services:
  backend:
    image: ghcr.io/coopstories/backend:f371f327afdca739b828b49c263ba2af40cd86dd
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
        restart: true
    environment:
      PORT: 4000
      FRONTEND_URL: $FRONTEND_URL
      DATABASE_URL: postgresql://postgres:$DB_PASSWORD@database:5432/coopstories

  database:
    image: postgres:14
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - coopstories_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: coopstories
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $DB_PASSWORD

volumes:
  coopstories_data:
