version: '3.8'

services:
  frontend:
    image: $FRONTEND_IMAGE_TAG
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    # TODO: Update this value with latest backend build
    image: ghcr.io/coopstories/backend:6131b166d253f3a24fcee811944efdc032ff02ec
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
        restart: true
    environment:
      PORT: 4000
      FRONTEND_URL: $FRONTEND_URL
      DATABASE_URL: postgresql://postgres:$DB_PASSWORD@database:5432/coopstories
    ports:
      - 4000:4000

  database:
    image: postgres:14
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - coopstories_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: coopstories
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $DB_PASSWORD

volumes:
  coopstories_data:
